version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${{secrets.TELEGRAM_TOKEN}}
    volumes:
      - "/codebase:/codebase"
      - "/storage:/storage"
    restart: always